// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: notifier/notifier.proto

package notifier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotifierClient is the client API for Notifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifierClient interface {
	LoadConfigs(ctx context.Context, in *LoadConfigsRequest, opts ...grpc.CallOption) (*LoadConfigsResponse, error)
	UpdateX509SVID(ctx context.Context, in *UpdateX509SVIDRequest, opts ...grpc.CallOption) (*UpdateX509SVIDResponse, error)
	UpdateJWTSVID(ctx context.Context, in *UpdateJWTSVIDRequest, opts ...grpc.CallOption) (*UpdateJWTSVIDResponse, error)
	UpdateJWTBundle(ctx context.Context, in *UpdateJWTBundleRequest, opts ...grpc.CallOption) (*UpdateJWTBundleResponse, error)
}

type notifierClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifierClient(cc grpc.ClientConnInterface) NotifierClient {
	return &notifierClient{cc}
}

func (c *notifierClient) LoadConfigs(ctx context.Context, in *LoadConfigsRequest, opts ...grpc.CallOption) (*LoadConfigsResponse, error) {
	out := new(LoadConfigsResponse)
	err := c.cc.Invoke(ctx, "/notifier.Notifier/LoadConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifierClient) UpdateX509SVID(ctx context.Context, in *UpdateX509SVIDRequest, opts ...grpc.CallOption) (*UpdateX509SVIDResponse, error) {
	out := new(UpdateX509SVIDResponse)
	err := c.cc.Invoke(ctx, "/notifier.Notifier/UpdateX509SVID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifierClient) UpdateJWTSVID(ctx context.Context, in *UpdateJWTSVIDRequest, opts ...grpc.CallOption) (*UpdateJWTSVIDResponse, error) {
	out := new(UpdateJWTSVIDResponse)
	err := c.cc.Invoke(ctx, "/notifier.Notifier/UpdateJWTSVID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifierClient) UpdateJWTBundle(ctx context.Context, in *UpdateJWTBundleRequest, opts ...grpc.CallOption) (*UpdateJWTBundleResponse, error) {
	out := new(UpdateJWTBundleResponse)
	err := c.cc.Invoke(ctx, "/notifier.Notifier/UpdateJWTBundle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifierServer is the server API for Notifier service.
// All implementations must embed UnimplementedNotifierServer
// for forward compatibility
type NotifierServer interface {
	LoadConfigs(context.Context, *LoadConfigsRequest) (*LoadConfigsResponse, error)
	UpdateX509SVID(context.Context, *UpdateX509SVIDRequest) (*UpdateX509SVIDResponse, error)
	UpdateJWTSVID(context.Context, *UpdateJWTSVIDRequest) (*UpdateJWTSVIDResponse, error)
	UpdateJWTBundle(context.Context, *UpdateJWTBundleRequest) (*UpdateJWTBundleResponse, error)
	mustEmbedUnimplementedNotifierServer()
}

// UnimplementedNotifierServer must be embedded to have forward compatible implementations.
type UnimplementedNotifierServer struct {
}

func (UnimplementedNotifierServer) LoadConfigs(context.Context, *LoadConfigsRequest) (*LoadConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadConfigs not implemented")
}
func (UnimplementedNotifierServer) UpdateX509SVID(context.Context, *UpdateX509SVIDRequest) (*UpdateX509SVIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateX509SVID not implemented")
}
func (UnimplementedNotifierServer) UpdateJWTSVID(context.Context, *UpdateJWTSVIDRequest) (*UpdateJWTSVIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJWTSVID not implemented")
}
func (UnimplementedNotifierServer) UpdateJWTBundle(context.Context, *UpdateJWTBundleRequest) (*UpdateJWTBundleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJWTBundle not implemented")
}
func (UnimplementedNotifierServer) mustEmbedUnimplementedNotifierServer() {}

// UnsafeNotifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifierServer will
// result in compilation errors.
type UnsafeNotifierServer interface {
	mustEmbedUnimplementedNotifierServer()
}

func RegisterNotifierServer(s grpc.ServiceRegistrar, srv NotifierServer) {
	s.RegisterService(&Notifier_ServiceDesc, srv)
}

func _Notifier_LoadConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServer).LoadConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notifier.Notifier/LoadConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServer).LoadConfigs(ctx, req.(*LoadConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notifier_UpdateX509SVID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateX509SVIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServer).UpdateX509SVID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notifier.Notifier/UpdateX509SVID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServer).UpdateX509SVID(ctx, req.(*UpdateX509SVIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notifier_UpdateJWTSVID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJWTSVIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServer).UpdateJWTSVID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notifier.Notifier/UpdateJWTSVID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServer).UpdateJWTSVID(ctx, req.(*UpdateJWTSVIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notifier_UpdateJWTBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJWTBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServer).UpdateJWTBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notifier.Notifier/UpdateJWTBundle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServer).UpdateJWTBundle(ctx, req.(*UpdateJWTBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Notifier_ServiceDesc is the grpc.ServiceDesc for Notifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notifier.Notifier",
	HandlerType: (*NotifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadConfigs",
			Handler:    _Notifier_LoadConfigs_Handler,
		},
		{
			MethodName: "UpdateX509SVID",
			Handler:    _Notifier_UpdateX509SVID_Handler,
		},
		{
			MethodName: "UpdateJWTSVID",
			Handler:    _Notifier_UpdateJWTSVID_Handler,
		},
		{
			MethodName: "UpdateJWTBundle",
			Handler:    _Notifier_UpdateJWTBundle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notifier/notifier.proto",
}
