version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directories:
      - /
      - /script/rpm
      - /test/integration/*
    schedule:
      interval: daily
    groups:
      docker-images:
        patterns:
          - "*"
    open-pull-requests-limit: 5
  - package-ecosystem: docker-compose
    directories:
      - /test/integration/*
    schedule:
      interval: daily
    groups:
      docker-compose-images:
        patterns:
          - "*"
    open-pull-requests-limit: 5
