run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 10m

issues:
  exclude-dirs:
    - testdata$
    - test/mock
  exclude-files:
    - ".*\\.pb\\.go"

linters:
  enable:
    - bodyclose
    - dupword
    - durationcheck
    - errorlint
    - gocritic
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  revive:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.0
