// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: plugin.proto

package helper_plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SpiffeHelper_PostConfigs_FullMethodName = "/helperPlugin.SpiffeHelper/PostConfigs"
)

// SpiffeHelperClient is the client API for SpiffeHelper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpiffeHelperClient interface {
	PostConfigs(ctx context.Context, in *ConfigsRequest, opts ...grpc.CallOption) (*Empty, error)
}

type spiffeHelperClient struct {
	cc grpc.ClientConnInterface
}

func NewSpiffeHelperClient(cc grpc.ClientConnInterface) SpiffeHelperClient {
	return &spiffeHelperClient{cc}
}

func (c *spiffeHelperClient) PostConfigs(ctx context.Context, in *ConfigsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, SpiffeHelper_PostConfigs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpiffeHelperServer is the server API for SpiffeHelper service.
// All implementations must embed UnimplementedSpiffeHelperServer
// for forward compatibility
type SpiffeHelperServer interface {
	PostConfigs(context.Context, *ConfigsRequest) (*Empty, error)
	mustEmbedUnimplementedSpiffeHelperServer()
}

// UnimplementedSpiffeHelperServer must be embedded to have forward compatible implementations.
type UnimplementedSpiffeHelperServer struct {
}

func (UnimplementedSpiffeHelperServer) PostConfigs(context.Context, *ConfigsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostConfigs not implemented")
}
func (UnimplementedSpiffeHelperServer) mustEmbedUnimplementedSpiffeHelperServer() {}

// UnsafeSpiffeHelperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpiffeHelperServer will
// result in compilation errors.
type UnsafeSpiffeHelperServer interface {
	mustEmbedUnimplementedSpiffeHelperServer()
}

func RegisterSpiffeHelperServer(s grpc.ServiceRegistrar, srv SpiffeHelperServer) {
	s.RegisterService(&SpiffeHelper_ServiceDesc, srv)
}

func _SpiffeHelper_PostConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiffeHelperServer).PostConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpiffeHelper_PostConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiffeHelperServer).PostConfigs(ctx, req.(*ConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpiffeHelper_ServiceDesc is the grpc.ServiceDesc for SpiffeHelper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpiffeHelper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helperPlugin.SpiffeHelper",
	HandlerType: (*SpiffeHelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostConfigs",
			Handler:    _SpiffeHelper_PostConfigs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
